apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkusasdf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkusasdf
    app.kubernetes.io/part-of: asdf
  name: java-quarkusasdf
  namespace: kkanova
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkusasdf
status:
  loadBalancer: {}
